# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'segment_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(467, 563)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setSizeIncrement(QtCore.QSize(2, 2))
        Dialog.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_2 = QtWidgets.QSplitter(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_2.setSizeIncrement(QtCore.QSize(2, 2))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.splitter_2.setFont(font)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.lineLengthRatio = QtWidgets.QLineEdit(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineLengthRatio.sizePolicy().hasHeightForWidth())
        self.lineLengthRatio.setSizePolicy(sizePolicy)
        self.lineLengthRatio.setSizeIncrement(QtCore.QSize(2, 2))
        self.lineLengthRatio.setObjectName("lineLengthRatio")
        self.lineDStar = QtWidgets.QLineEdit(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineDStar.sizePolicy().hasHeightForWidth())
        self.lineDStar.setSizePolicy(sizePolicy)
        self.lineDStar.setSizeIncrement(QtCore.QSize(2, 2))
        self.lineDStar.setObjectName("lineDStar")
        self.lineDEnd = QtWidgets.QLineEdit(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineDEnd.sizePolicy().hasHeightForWidth())
        self.lineDEnd.setSizePolicy(sizePolicy)
        self.lineDEnd.setSizeIncrement(QtCore.QSize(2, 2))
        self.lineDEnd.setObjectName("lineDEnd")
        self.lineTStar = QtWidgets.QLineEdit(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineTStar.sizePolicy().hasHeightForWidth())
        self.lineTStar.setSizePolicy(sizePolicy)
        self.lineTStar.setSizeIncrement(QtCore.QSize(2, 2))
        self.lineTStar.setObjectName("lineTStar")
        self.lineTend = QtWidgets.QLineEdit(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineTend.sizePolicy().hasHeightForWidth())
        self.lineTend.setSizePolicy(sizePolicy)
        self.lineTend.setSizeIncrement(QtCore.QSize(2, 2))
        self.lineTend.setObjectName("lineTend")
        self.lineRho = QtWidgets.QLineEdit(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineRho.sizePolicy().hasHeightForWidth())
        self.lineRho.setSizePolicy(sizePolicy)
        self.lineRho.setSizeIncrement(QtCore.QSize(2, 2))
        self.lineRho.setObjectName("lineRho")
        self.lineE = QtWidgets.QLineEdit(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineE.sizePolicy().hasHeightForWidth())
        self.lineE.setSizePolicy(sizePolicy)
        self.lineE.setSizeIncrement(QtCore.QSize(2, 2))
        self.lineE.setObjectName("lineE")
        self.lineG = QtWidgets.QLineEdit(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineG.sizePolicy().hasHeightForWidth())
        self.lineG.setSizePolicy(sizePolicy)
        self.lineG.setSizeIncrement(QtCore.QSize(2, 2))
        self.lineG.setObjectName("lineG")
        self.lineAlphaS = QtWidgets.QLineEdit(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineAlphaS.sizePolicy().hasHeightForWidth())
        self.lineAlphaS.setSizePolicy(sizePolicy)
        self.lineAlphaS.setSizeIncrement(QtCore.QSize(2, 2))
        self.lineAlphaS.setObjectName("lineAlphaS")
        self.lineAlphaV = QtWidgets.QLineEdit(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineAlphaV.sizePolicy().hasHeightForWidth())
        self.lineAlphaV.setSizePolicy(sizePolicy)
        self.lineAlphaV.setSizeIncrement(QtCore.QSize(2, 2))
        self.lineAlphaV.setObjectName("lineAlphaV")
        self.lineScfStart = QtWidgets.QLineEdit(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineScfStart.sizePolicy().hasHeightForWidth())
        self.lineScfStart.setSizePolicy(sizePolicy)
        self.lineScfStart.setSizeIncrement(QtCore.QSize(2, 2))
        self.lineScfStart.setObjectName("lineScfStart")
        self.lineScfEnd = QtWidgets.QLineEdit(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineScfEnd.sizePolicy().hasHeightForWidth())
        self.lineScfEnd.setSizePolicy(sizePolicy)
        self.lineScfEnd.setSizeIncrement(QtCore.QSize(2, 2))
        self.lineScfEnd.setObjectName("lineScfEnd")
        self.gridLayout.addWidget(self.splitter_2, 1, 1, 1, 1)
        self.lblTitle = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitle.sizePolicy().hasHeightForWidth())
        self.lblTitle.setSizePolicy(sizePolicy)
        self.lblTitle.setSizeIncrement(QtCore.QSize(2, 2))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.lblTitle.setFont(font)
        self.lblTitle.setScaledContents(True)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setWordWrap(True)
        self.lblTitle.setObjectName("lblTitle")
        self.gridLayout.addWidget(self.lblTitle, 0, 0, 1, 2)
        self.splitter = QtWidgets.QSplitter(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setSizeIncrement(QtCore.QSize(2, 2))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.splitter.setFont(font)
        self.splitter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.lblLengthRatio = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLengthRatio.sizePolicy().hasHeightForWidth())
        self.lblLengthRatio.setSizePolicy(sizePolicy)
        self.lblLengthRatio.setSizeIncrement(QtCore.QSize(2, 2))
        self.lblLengthRatio.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLengthRatio.setObjectName("lblLengthRatio")
        self.lblDStar = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDStar.sizePolicy().hasHeightForWidth())
        self.lblDStar.setSizePolicy(sizePolicy)
        self.lblDStar.setSizeIncrement(QtCore.QSize(2, 2))
        self.lblDStar.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDStar.setObjectName("lblDStar")
        self.lblDend = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDend.sizePolicy().hasHeightForWidth())
        self.lblDend.setSizePolicy(sizePolicy)
        self.lblDend.setSizeIncrement(QtCore.QSize(2, 2))
        self.lblDend.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDend.setObjectName("lblDend")
        self.lblTStar = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTStar.sizePolicy().hasHeightForWidth())
        self.lblTStar.setSizePolicy(sizePolicy)
        self.lblTStar.setSizeIncrement(QtCore.QSize(2, 2))
        self.lblTStar.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTStar.setObjectName("lblTStar")
        self.lblTEnd = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTEnd.sizePolicy().hasHeightForWidth())
        self.lblTEnd.setSizePolicy(sizePolicy)
        self.lblTEnd.setSizeIncrement(QtCore.QSize(2, 2))
        self.lblTEnd.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTEnd.setObjectName("lblTEnd")
        self.lblrho = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblrho.sizePolicy().hasHeightForWidth())
        self.lblrho.setSizePolicy(sizePolicy)
        self.lblrho.setSizeIncrement(QtCore.QSize(2, 2))
        self.lblrho.setAlignment(QtCore.Qt.AlignCenter)
        self.lblrho.setObjectName("lblrho")
        self.lblE = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblE.sizePolicy().hasHeightForWidth())
        self.lblE.setSizePolicy(sizePolicy)
        self.lblE.setSizeIncrement(QtCore.QSize(2, 2))
        self.lblE.setAlignment(QtCore.Qt.AlignCenter)
        self.lblE.setObjectName("lblE")
        self.lbG = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbG.sizePolicy().hasHeightForWidth())
        self.lbG.setSizePolicy(sizePolicy)
        self.lbG.setSizeIncrement(QtCore.QSize(2, 2))
        self.lbG.setAlignment(QtCore.Qt.AlignCenter)
        self.lbG.setObjectName("lbG")
        self.lblAlphaS = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAlphaS.sizePolicy().hasHeightForWidth())
        self.lblAlphaS.setSizePolicy(sizePolicy)
        self.lblAlphaS.setSizeIncrement(QtCore.QSize(2, 2))
        self.lblAlphaS.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAlphaS.setObjectName("lblAlphaS")
        self.lblAlphaV = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAlphaV.sizePolicy().hasHeightForWidth())
        self.lblAlphaV.setSizePolicy(sizePolicy)
        self.lblAlphaV.setSizeIncrement(QtCore.QSize(2, 2))
        self.lblAlphaV.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAlphaV.setObjectName("lblAlphaV")
        self.lblScfStart = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblScfStart.sizePolicy().hasHeightForWidth())
        self.lblScfStart.setSizePolicy(sizePolicy)
        self.lblScfStart.setSizeIncrement(QtCore.QSize(2, 2))
        self.lblScfStart.setAlignment(QtCore.Qt.AlignCenter)
        self.lblScfStart.setObjectName("lblScfStart")
        self.lblScfEnd = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblScfEnd.sizePolicy().hasHeightForWidth())
        self.lblScfEnd.setSizePolicy(sizePolicy)
        self.lblScfEnd.setSizeIncrement(QtCore.QSize(2, 2))
        self.lblScfEnd.setAlignment(QtCore.Qt.AlignCenter)
        self.lblScfEnd.setObjectName("lblScfEnd")
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setSizeIncrement(QtCore.QSize(2, 2))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)
        self.lblLengthRatio.setBuddy(self.lineLengthRatio)
        self.lblDStar.setBuddy(self.lineDStar)
        self.lblDend.setBuddy(self.lineDEnd)
        self.lblTStar.setBuddy(self.lineTStar)
        self.lblTEnd.setBuddy(self.lineTend)
        self.lblrho.setBuddy(self.lineRho)
        self.lblE.setBuddy(self.lineE)
        self.lbG.setBuddy(self.lineG)
        self.lblAlphaS.setBuddy(self.lineAlphaS)
        self.lblAlphaV.setBuddy(self.lineAlphaV)
        self.lblScfStart.setBuddy(self.lineScfStart)
        self.lblScfEnd.setBuddy(self.lineScfEnd)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Segment Data"))
        self.lblTitle.setText(_translate("Dialog", "Enter data for segment 1"))
        self.lblLengthRatio.setText(_translate("Dialog", "Length Ratio"))
        self.lblDStar.setText(_translate("Dialog", "<html>\n"
"<body>D<sup>*</sup></body>\n"
"</html>"))
        self.lblDend.setToolTip(_translate("Dialog", "It\'s the diameter of the end"))
        self.lblDend.setText(_translate("Dialog", "<html>\n"
"<body>\n"
"\n"
"\n"
"\n"
"D<sub>end</sub>\n"
"\n"
"\n"
"</body>\n"
"</html>"))
        self.lblTStar.setToolTip(_translate("Dialog", "It\'s thickness"))
        self.lblTStar.setText(_translate("Dialog", "<html>\n"
"<body>\n"
"\n"
"\n"
"\n"
"t<sup>*</sup>\n"
"\n"
"\n"
"</body>\n"
"</html>"))
        self.lblTEnd.setText(_translate("Dialog", "<html>\n"
"<body>\n"
"\n"
"\n"
"\n"
"t<sub>end</sub>\n"
"\n"
"\n"
"</body>\n"
"</html>"))
        self.lblrho.setToolTip(_translate("Dialog", "It\'s the density of the member"))
        self.lblrho.setText(_translate("Dialog", "<html>\n"
"<body>\n"
"\n"
"\n"
"\n"
"<font face=symbol>r</font>\n"
"\n"
"\n"
"</body>\n"
"</html>"))
        self.lblE.setToolTip(_translate("Dialog", "It\'s the density of the member"))
        self.lblE.setText(_translate("Dialog", "E"))
        self.lbG.setToolTip(_translate("Dialog", "It\'s the density of the member"))
        self.lbG.setText(_translate("Dialog", "G"))
        self.lblAlphaS.setToolTip(_translate("Dialog", "It\'s the density of the member"))
        self.lblAlphaS.setText(_translate("Dialog", "<html>\n"
"<body>\n"
"\n"
"\n"
"\n"
"<font face=symbol>a</font><sub>s</sub>\n"
"\n"
"\n"
"</body>\n"
"</html>\n"
""))
        self.lblAlphaV.setToolTip(_translate("Dialog", "It\'s the density of the member"))
        self.lblAlphaV.setText(_translate("Dialog", "<html>\n"
"<body>\n"
"\n"
"\n"
"\n"
"<font face=symbol>a</font><sub>v</sub>\n"
"\n"
"\n"
"</body>\n"
"</html>"))
        self.lblScfStart.setToolTip(_translate("Dialog", "It\'s the density of the member"))
        self.lblScfStart.setText(_translate("Dialog", "<html>\n"
"<body>\n"
"\n"
"\n"
"\n"
"SCF<sub>start</sub>\n"
"\n"
"\n"
"</body>\n"
"</html>"))
        self.lblScfEnd.setToolTip(_translate("Dialog", "It\'s the density of the member"))
        self.lblScfEnd.setText(_translate("Dialog", "<html>\n"
"<body>\n"
"\n"
"\n"
"\n"
"SCF<sub>end</sub>\n"
"\n"
"\n"
"</body>\n"
"</html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
