from PyQt5 import QtCore, QtGui, QtWidgets
from sqlalchemy import null
from rigid_body import *
import numpy as np


class Ui_Dialog1(object):
    
    def __init__(self,ui_2):
        self.ui_2 = ui_2
        
    def setupUi(self, Dialog1):
        Dialog1.setObjectName("Dialog1")
        Dialog1.resize(509, 448)
        Dialog1.setMouseTracking(True)
        Dialog1.setTabletTracking(False)
        Dialog1.setAcceptDrops(True)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog1)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(180, 380, 201, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.horizontalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.label = QtWidgets.QLabel(Dialog1)
        self.label.setGeometry(QtCore.QRect(200, 10, 55, 16))
        self.label.setObjectName("label")
        self.label_14 = QtWidgets.QLabel(Dialog1)
        self.label_14.setGeometry(QtCore.QRect(400, 10, 55, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog1)
        self.label_15.setGeometry(QtCore.QRect(70, 40, 55, 16))
        self.label_15.setObjectName("label_15")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Dialog1)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(120, 80, 184, 22))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.d1_RB1_x = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.d1_RB1_x.setObjectName("d1_RB1_x")
        self.gridLayout_3.addWidget(self.d1_RB1_x, 1, 0, 1, 1)
        self.d1_RB1_y = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.d1_RB1_y.setObjectName("d1_RB1_y")
        self.gridLayout_3.addWidget(self.d1_RB1_y, 1, 1, 1, 1)
        self.d1_RB1_z = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.d1_RB1_z.setObjectName("d1_RB1_z")
        self.gridLayout_3.addWidget(self.d1_RB1_z, 1, 2, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(Dialog1)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(120, 40, 184, 22))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pos_RB1_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.pos_RB1_1.setObjectName("pos_RB1_1")
        self.gridLayout_6.addWidget(self.pos_RB1_1, 1, 0, 1, 1)
        self.pos_RB1_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.pos_RB1_2.setToolTipDuration(-1)
        self.pos_RB1_2.setObjectName("pos_RB1_2")
        self.gridLayout_6.addWidget(self.pos_RB1_2, 1, 1, 1, 1)
        self.pos_RB1_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.pos_RB1_3.setToolTipDuration(-1)
        self.pos_RB1_3.setObjectName("pos_RB1_3")
        self.gridLayout_6.addWidget(self.pos_RB1_3, 1, 2, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(Dialog1)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(320, 40, 184, 22))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pos_RB2_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.pos_RB2_1.setObjectName("pos_RB2_1")
        self.gridLayout_7.addWidget(self.pos_RB2_1, 1, 0, 1, 1)
        self.pos_RB2_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.pos_RB2_2.setObjectName("pos_RB2_2")
        self.gridLayout_7.addWidget(self.pos_RB2_2, 1, 1, 1, 1)
        self.pos_RB2_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.pos_RB2_3.setObjectName("pos_RB2_3")
        self.gridLayout_7.addWidget(self.pos_RB2_3, 1, 2, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(Dialog1)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(320, 80, 184, 22))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.d1_RB2_x = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.d1_RB2_x.setObjectName("d1_RB2_x")
        self.gridLayout_5.addWidget(self.d1_RB2_x, 1, 0, 1, 1)
        self.d1_RB2_y = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.d1_RB2_y.setObjectName("d1_RB2_y")
        self.gridLayout_5.addWidget(self.d1_RB2_y, 1, 1, 1, 1)
        self.d1_RB2_z = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.d1_RB2_z.setObjectName("d1_RB2_z")
        self.gridLayout_5.addWidget(self.d1_RB2_z, 1, 2, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(Dialog1)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(320, 110, 184, 22))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.d2_RB2_x = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.d2_RB2_x.setObjectName("d2_RB2_x")
        self.gridLayout_8.addWidget(self.d2_RB2_x, 1, 0, 1, 1)
        self.d2_RB2_y = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.d2_RB2_y.setObjectName("d2_RB2_y")
        self.gridLayout_8.addWidget(self.d2_RB2_y, 1, 1, 1, 1)
        self.d2_RB2_z = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.d2_RB2_z.setObjectName("d2_RB2_z")
        self.gridLayout_8.addWidget(self.d2_RB2_z, 1, 2, 1, 1)
        self.gridLayoutWidget_9 = QtWidgets.QWidget(Dialog1)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(120, 110, 184, 22))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.d2_RB1_x = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.d2_RB1_x.setObjectName("d2_RB1_x")
        self.gridLayout_9.addWidget(self.d2_RB1_x, 1, 0, 1, 1)
        self.d2_RB1_y = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.d2_RB1_y.setObjectName("d2_RB1_y")
        self.gridLayout_9.addWidget(self.d2_RB1_y, 1, 1, 1, 1)
        self.d2_RB1_z = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.d2_RB1_z.setObjectName("d2_RB1_z")
        self.gridLayout_9.addWidget(self.d2_RB1_z, 1, 2, 1, 1)
        self.gridLayoutWidget_10 = QtWidgets.QWidget(Dialog1)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(320, 140, 184, 22))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.d3_RB2_x = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.d3_RB2_x.setObjectName("d3_RB2_x")
        self.gridLayout_10.addWidget(self.d3_RB2_x, 1, 0, 1, 1)
        self.d3_RB2_y = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.d3_RB2_y.setObjectName("d3_RB2_y")
        self.gridLayout_10.addWidget(self.d3_RB2_y, 1, 1, 1, 1)
        self.d3_RB2_z = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.d3_RB2_z.setObjectName("d3_RB2_z")
        self.gridLayout_10.addWidget(self.d3_RB2_z, 1, 2, 1, 1)
        self.gridLayoutWidget_11 = QtWidgets.QWidget(Dialog1)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(120, 140, 184, 22))
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.d3_RB1_x = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.d3_RB1_x.setObjectName("d3_RB1_x")
        self.gridLayout_11.addWidget(self.d3_RB1_x, 1, 0, 1, 1)
        self.d3_RB1_y = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.d3_RB1_y.setObjectName("d3_RB1_y")
        self.gridLayout_11.addWidget(self.d3_RB1_y, 1, 1, 1, 1)
        self.d3_RB1_z = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.d3_RB1_z.setObjectName("d3_RB1_z")
        self.gridLayout_11.addWidget(self.d3_RB1_z, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog1)
        self.label_4.setGeometry(QtCore.QRect(60, 80, 61, 20))
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.mass_RB1 = QtWidgets.QLineEdit(Dialog1)
        self.mass_RB1.setGeometry(QtCore.QRect(120, 180, 181, 20))
        self.mass_RB1.setObjectName("mass_RB1")
        self.mass_RB2 = QtWidgets.QLineEdit(Dialog1)
        self.mass_RB2.setGeometry(QtCore.QRect(320, 180, 181, 20))
        self.mass_RB2.setObjectName("mass_RB2")
        self.label_2 = QtWidgets.QLabel(Dialog1)
        self.label_2.setGeometry(QtCore.QRect(80, 180, 21, 20))
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(Dialog1)
        self.label_7.setGeometry(QtCore.QRect(0, 210, 81, 37))
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(Dialog1)
        self.label_5.setGeometry(QtCore.QRect(60, 110, 61, 20))
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog1)
        self.label_6.setGeometry(QtCore.QRect(60, 140, 61, 20))
        self.label_6.setScaledContents(False)
        self.label_6.setObjectName("label_6")
        self.lineEdit_36 = QtWidgets.QLineEdit(Dialog1)
        self.lineEdit_36.setGeometry(QtCore.QRect(320, 220, 181, 20))
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.lineEdit_37 = QtWidgets.QLineEdit(Dialog1)
        self.lineEdit_37.setGeometry(QtCore.QRect(120, 220, 181, 20))
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_38 = QtWidgets.QLineEdit(Dialog1)
        self.lineEdit_38.setGeometry(QtCore.QRect(320, 250, 181, 20))
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_39 = QtWidgets.QLineEdit(Dialog1)
        self.lineEdit_39.setGeometry(QtCore.QRect(120, 250, 181, 20))
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.lineEdit_40 = QtWidgets.QLineEdit(Dialog1)
        self.lineEdit_40.setGeometry(QtCore.QRect(120, 280, 181, 20))
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.lineEdit_41 = QtWidgets.QLineEdit(Dialog1)
        self.lineEdit_41.setGeometry(QtCore.QRect(320, 310, 181, 20))
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.lineEdit_42 = QtWidgets.QLineEdit(Dialog1)
        self.lineEdit_42.setGeometry(QtCore.QRect(120, 310, 181, 20))
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.lineEdit_43 = QtWidgets.QLineEdit(Dialog1)
        self.lineEdit_43.setGeometry(QtCore.QRect(320, 280, 181, 20))
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.lineEdit_44 = QtWidgets.QLineEdit(Dialog1)
        self.lineEdit_44.setGeometry(QtCore.QRect(320, 340, 181, 20))
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.lineEdit_45 = QtWidgets.QLineEdit(Dialog1)
        self.lineEdit_45.setGeometry(QtCore.QRect(120, 340, 181, 20))
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.lineEdit_46 = QtWidgets.QLineEdit(Dialog1)
        self.lineEdit_46.setGeometry(QtCore.QRect(120, 370, 181, 20))
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.lineEdit_47 = QtWidgets.QLineEdit(Dialog1)
        self.lineEdit_47.setGeometry(QtCore.QRect(320, 370, 181, 20))
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.label_8 = QtWidgets.QLabel(Dialog1)
        self.label_8.setGeometry(QtCore.QRect(90, 220, 19, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog1)
        self.label_9.setGeometry(QtCore.QRect(90, 250, 19, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog1)
        self.label_10.setGeometry(QtCore.QRect(90, 280, 19, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog1)
        self.label_11.setGeometry(QtCore.QRect(90, 310, 19, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog1)
        self.label_12.setGeometry(QtCore.QRect(90, 340, 19, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog1)
        self.label_13.setGeometry(QtCore.QRect(90, 370, 19, 20))
        self.label_13.setObjectName("label_13")

        self.retranslateUi(Dialog1)
        self.func_call(self)
        self.buttonBox.accepted.connect(Dialog1.accept)
        self.buttonBox.rejected.connect(Dialog1.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog1)

    @staticmethod
    def func_call(self):
        I11_cm = 9437478.00823881
        I22_cm = 9808155.98764257
        I33_cm = 9780449.1838345
        I12_cm = 446585.459454508
        I13_cm = 1960561.61974822
        I23_cm = -232499.00841237
        II_cm = np.asarray([[I11_cm, I12_cm, I13_cm],[I12_cm, I22_cm, I23_cm],[I13_cm, I23_cm, I33_cm]])
        #create an object of rigif body
        self.ui_2.set_positions({0:np.array([4.68800,	0.0	,148.822]),1:np.array( [-10.93417,	0.0,	150.07473])})
        self.ui_2.set_directors_x({0:np.array([1.0,	0.0,	0.0]),1:np.array([0.707107, 0.707107, 0.0])})
        self.ui_2.set_directors_y({0:np.array([0.0,	1.0,	0.0]),1:np.array([-0.707107, 0.707107, 0.0])})
        self.ui_2.set_directors_z({0:np.array([0.0,	0.0,	1.0]),1:np.array([0.0, 0.0, 1.0])})
        self.ui_2.set_masses([820888.0, 190000.0])
        self.ui_2.set_inertias({0:II_cm,1:II_cm})
        self.ui_2.set_prop_id_rigid_bodies_map({0:0,1:1})


    def retranslateUi(self, Dialog1):
        _translate = QtCore.QCoreApplication.translate
        Dialog1.setWindowTitle(_translate("Dialog1", "Input Parameters"))
        self.label.setText(_translate("Dialog1", "RB1"))
        self.label_14.setText(_translate("Dialog1", "RB2"))
        self.label_15.setText(_translate("Dialog1", "Position"))
        self.d1_RB1_x.setToolTip(_translate("Dialog1", "<html><head/><body><p>3D coordinates of d1 for first rigid body</p></body></html>"))
        self.d1_RB1_y.setToolTip(_translate("Dialog1", "<html><head/><body><p>3D coordinates of d1 for first rigid body</p></body></html>"))
        self.d1_RB1_z.setToolTip(_translate("Dialog1", "<html><head/><body><p>3D coordinates of d1 for first rigid body</p></body></html>"))
        self.pos_RB1_1.setToolTip(_translate("Dialog1", "<html><head/><body><p>Enter the 3D coordinates of first rigid body</p></body></html>"))
        self.pos_RB1_2.setToolTip(_translate("Dialog1", "<html><head/><body><p>Enter the 3D coordinates of first rigid body</p></body></html>"))
        self.pos_RB1_3.setToolTip(_translate("Dialog1", "<html><head/><body><p>Enter the 3D coordinates of first rigid body</p></body></html>"))
        self.pos_RB2_1.setToolTip(_translate("Dialog1", "<html><head/><body><p>Enter the 3D coordinates of second rigid body</p></body></html>"))
        self.pos_RB2_2.setToolTip(_translate("Dialog1", "<html><head/><body><p>Enter the 3D coordinates of second rigid body</p></body></html>"))
        self.pos_RB2_3.setToolTip(_translate("Dialog1", "<html><head/><body><p>Enter the 3D coordinates of second rigid body</p></body></html>"))
        self.d1_RB2_x.setToolTip(_translate("Dialog1", "<html><head/><body><p>3D coordinates of d1 for second rigid body</p></body></html>"))
        self.d1_RB2_y.setToolTip(_translate("Dialog1", "<html><head/><body><p>3D coordinates of d1 for second rigid body</p></body></html>"))
        self.d1_RB2_z.setToolTip(_translate("Dialog1", "<html><head/><body><p>3D coordinates of d1 for second rigid body</p></body></html>"))
        self.d2_RB2_x.setToolTip(_translate("Dialog1", "<html><head/><body><p>3D coordinates of d2 for second rigid body</p></body></html>"))
        self.d2_RB2_y.setToolTip(_translate("Dialog1", "<html><head/><body><p>3D coordinates of d2 for second rigid body</p></body></html>"))
        self.d2_RB2_z.setToolTip(_translate("Dialog1", "<html><head/><body><p>3D coordinates of d2 for second rigid body</p></body></html>"))
        self.d2_RB1_x.setToolTip(_translate("Dialog1", "<html><head/><body><p>3D coordinates of d2 for first rigid body</p></body></html>"))
        self.d2_RB1_y.setToolTip(_translate("Dialog1", "<html><head/><body><p>3D coordinates of d2 for first rigid body</p></body></html>"))
        self.d2_RB1_z.setToolTip(_translate("Dialog1", "<html><head/><body><p>3D coordinates of d2 for first rigid body</p></body></html>"))
        self.d3_RB2_x.setToolTip(_translate("Dialog1", "<html><head/><body><p>3D coordinates of d3 for second rigid body</p></body></html>"))
        self.d3_RB2_y.setToolTip(_translate("Dialog1", "<html><head/><body><p>3D coordinates of d3 for second rigid body</p></body></html>"))
        self.d3_RB2_z.setToolTip(_translate("Dialog1", "<html><head/><body><p>3D coordinates of d3 for second rigid body</p></body></html>"))
        self.d3_RB1_x.setToolTip(_translate("Dialog1", "<html><head/><body><p>3D coordinates of d3 for first rigid body</p></body></html>"))
        self.d3_RB1_y.setToolTip(_translate("Dialog1", "<html><head/><body><p>3D coordinates of d3 for first rigid body</p></body></html>"))
        self.d3_RB1_z.setToolTip(_translate("Dialog1", "<html><head/><body><p>3D coordinates of d3 for first rigid body</p></body></html>"))
        self.label_4.setText(_translate("Dialog1", "Director d1"))
        self.mass_RB1.setToolTip(_translate("Dialog1", "<html><head/><body><p>Enter the mass for first rigid body</p></body></html>"))
        self.mass_RB2.setToolTip(_translate("Dialog1", "<html><head/><body><p>Enter the mass for second rigid body</p></body></html>"))
        self.label_2.setText(_translate("Dialog1", "Mass"))
        self.label_7.setText(_translate("Dialog1", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Second Moment of Inertia</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog1", "Director d2"))
        self.label_6.setText(_translate("Dialog1", "Director d3"))
        self.label_8.setText(_translate("Dialog1", "I_11"))
        self.label_9.setText(_translate("Dialog1", "I_22"))
        self.label_10.setText(_translate("Dialog1", "I_33"))
        self.label_11.setText(_translate("Dialog1", "I_12"))
        self.label_12.setText(_translate("Dialog1", "I_12"))
        self.label_13.setText(_translate("Dialog1", "I_23"))


if __name__ == "__main__":
    ui_2 = Ui_Dialog1()
