# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Necelle_Test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from pathlib import Path
import os
import matplotlib.pyplot as plt
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QDialog
from rigid_body import RigidBody
from Necelle_RB_3DInputPara import Ui_Dialog1

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(385, 369)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_RB = QtWidgets.QLabel(self.centralwidget)
        self.label_RB.setGeometry(QtCore.QRect(30, 40, 161, 16))
        self.label_RB.setObjectName("label_RB")
        self.label_CP = QtWidgets.QLabel(self.centralwidget)
        self.label_CP.setGeometry(QtCore.QRect(30, 70, 191, 31))
        self.label_CP.setObjectName("label_CP")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(230, 40, 81, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(230, 80, 81, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.bt1_genFile = QtWidgets.QPushButton(self.centralwidget)
        self.bt1_genFile.setGeometry(QtCore.QRect(10, 290, 231, 51))
        self.bt1_genFile.setObjectName("bt1_genFile")
        
        self.bt2_genTable = QtWidgets.QPushButton(self.centralwidget)
        self.bt2_genTable.setGeometry(QtCore.QRect(100, 150, 171, 41))
        self.bt2_genTable.setDefault(True)
        self.bt2_genTable.setObjectName("bt2_GenTable")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.bt2_genTable.clicked.connect(self.table_dialog)

        self.bt1_genFile.clicked.connect(RigidBody.write_data(self))

    def table_dialog(self):
        """
        Launching the dialogue box for table
        """
        tab_dlg = TableDlg(self)
        tab_dlg.exec_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NecellePage"))
        self.label_RB.setText(_translate("MainWindow", "<html><head/><body><p>Number of Rigid Bodies</p></body></html>"))
        self.label_CP.setText(_translate("MainWindow", "<html><head/><body><p>Number of Cross-Properties</p></body></html>"))
        self.bt1_genFile.setText(_translate("MainWindow", "Generate File"))
        self.bt2_genTable.setText(_translate("MainWindow", "Generate Table"))

class TableDlg(QDialog):
    def __init__(self,parent):
        super().__init__(parent)
        # Creating an instance of the GUI
        self.ui = Ui_Dialog1()
        # Run the .setupUi() method to show the GUI
        self.ui.setupUi(self)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
